name: Deploy QA
on:
  push:
    branches: [main, feat/*]
jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    outputs: 
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build
        id: build
        run: |
          IMAGE_TAG=main-$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "building image $IMAGE_TAG"
      - name: Push
        run: |
          echo "pushing image $IMAGE_TAG"
  deploy-qa:
    needs: build-and-push
    uses: ./.github/workflows/deploy.yml
    with: 
      environment: qa
      image-tag: ${{ needs.build-and-push.outputs.image-tag }} 

