name: Deploy Prod
on: 
  workflow_call:
concurrency: 
  group: production
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    environment: production
    env: 
      TRIGGER_ID: "${{ vars.TRIGGER_GROUP }}/${{ vars.TRIGGER_PRODUCT }}/${{ vars.TRIGGER_ENV }}/${{ vars.TRIGGER_LOCATION }}"
    steps: 
      - name: Deploy
        run: | 
          echo ${GITHUB_SHA}
          echo "deploying image ${{ needs.build-and-push.outputs.image_tag }} to ${{ env.TRIGGER_ID }}"
          echo "### Deployed ${{ needs.build-and-push.outputs.image_tag }} to ${{ env.TRIGGER_ID }} :rocket:" >> $GITHUB_STEP_SUMMARY
          if [ "${{ secrets.MY_SECRET }}" = "paul" ]; then
            echo "secret is paul" > result.txt
          else
            echo "secret messed up" > result.txt
          fi
  create-release-tag: 
    name: Create Release Tag
    needs: deploy
    runs-on: ubuntu-latest
    steps: 
      - name: Tag
        run: echo "create release tag prod only ${GITHUB_SHA}?"
  post-deploy-tests:
    name: Post Deploy Tests
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check deploy complete
        run: echo "wait til pods updated with new image"
      - name: Smoke test env
        run: echo "here we automate tests that new version up and running${GITHUB_SHA}"
