name: Deploy QA
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    outputs: 
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build
        id: build
        run: |
          IMAGE_TAG=main-$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "building image $IMAGE_TAG"
      - name: Push
        run: |
          echo "pushing image $IMAGE_TAG"
  deploy:
    name: Deploy to Environment
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: qa
    env: 
      TRIGGER_ID: "${{ vars.TRIGGER_GROUP }}/${{ vars.TRIGGER_PRODUCT }}/${{ vars.TRIGGER_ENV }}/${{ vars.TRIGGER_LOCATION }}"
    steps: 
      - name: Deploy
        run: | 
          echo "deploying image ${{ needs.build-and-push.outputs.image_tag }} to ${{ env.TRIGGER_ID }}"
          echo "### Deployed ${{ needs.build-and-push.outputs.image_tag }} to ${{ env.TRIGGER_ID }} :rocket:" >> $GITHUB_STEP_SUMMARY
  post-deploy-tests:
    name: Post Deploy Tests
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check deploy complete
        run: echo "wait til pods updated with new image"
      - name: Smoke test env
        run: echo "here we automate tests that new version up and running"
  prepare-prod-release: 
    name: Prepare Prod Release
    needs: post-deploy-tests
    uses: ./.github/workflows/deploy-prod.yml
